import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import Head from "./head";
import {GlobalProvider} from "@/app/GlobalProvider";
import Script from "next/script";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <Head/>
        <body><GlobalProvider>{children}</GlobalProvider>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></Script>
        <Script src="https://kit.fontawesome.com/0337cb34f9.js"></Script>
        </body>
        </html>
    );
}
